x = {"companies": {"totalCount": 538, "count": 35, "list": [
     {"name": "Calfas Construction, Steven", "mid": "0136922977", "emid": "mr0k9nh",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mr0k9nh/calfas-construction-steven", "claimStatus": "UNCLAIMED",
      "location": {"address": "3320 South Cochise Avenue", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64057"}, "contactInfo": {"phone": "8167951859"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E0209000", "description": "Home Builders"}}, "serviceAreasString": ""},
     {"name": "R H Smart Construction", "mid": "0029959585", "emid": "mttf8fh",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mttf8fh/r-h-smart-construction", "claimStatus": "UNCLAIMED",
      "location": {"address": "1714 North Ashley Drive", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64058"}, "contactInfo": {"phone": "8167966067"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E0209000", "description": "Home Builders"}}, "serviceAreasString": ""},
     {"name": "Cullens Construction", "mid": "0028934995", "emid": "mtmbkhz",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mtmbkhz/cullens-construction", "claimStatus": "UNCLAIMED",
      "location": {"address": "11303 East Truman Road", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64050"}, "contactInfo": {"phone": "8165299458"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E0209000", "description": "Home Builders"}}, "serviceAreasString": ""},
     {"name": "Vern Thompson Construction", "mid": "0012820335", "emid": "mmfpbdx",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mmfpbdx/vern-thompson-construction", "claimStatus": "UNCLAIMED",
      "location": {"address": "19700 East Bundschu Road", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64056"}, "contactInfo": {"phone": "8167964404"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E0209000", "description": "Home Builders"}}, "serviceAreasString": ""},
     {"name": "D & M Doors Inc", "mid": "0013470189", "emid": "mm2gr5h",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mm2gr5h/d-m-doors-inc", "claimStatus": "UNCLAIMED",
      "location": {"address": "910 South Queen Ridge Drive", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64050"}, "contactInfo": {"phone": "8162524191"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E00D3", "description": "Lumber and Other Building Materials Dealers"},
                   "sicm": {"code": "E00D305N", "description": "Garage Doors"}}, "serviceAreasString": ""},
     {"name": "George Stewart Construction", "mid": "0024657392", "emid": "mm5nnty",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mm5nnty/george-stewart-construction", "claimStatus": "UNCLAIMED",
      "location": {"address": "712 South Alexander Road", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64056"}, "contactInfo": {}, "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E0209000", "description": "Home Builders"}}, "serviceAreasString": ""},
     {"name": "Summit Masonry Inc", "mid": "0026763262", "emid": "mmq6c7t",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mmq6c7t/summit-masonry-inc", "claimStatus": "UNCLAIMED",
      "location": {"address": "2623 South State Route 7", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64057"},
      "contactInfo": {"phone": "8162241010", "website": "http://Summitmasonryinc.com"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E02E5", "description": "Masonry, Stone Setting, and Other Stone Work"},
                   "sicm": {"code": "E02E5000", "description": "Masonry Contractors"}}, "serviceAreasString": ""},
     {"name": "Jdi Concrete", "mid": "0207815336", "emid": "mhkm0t3",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mhkm0t3/jdi-concrete", "claimStatus": "UNCLAIMED",
      "location": {"address": "9514 East 23rd Street South", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64052"},
      "contactInfo": {"phone": "8166994081", "website": "http://www.jdiconcrete.com"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0303", "description": "Concrete Work"},
                   "sicm": {"code": "E030308D", "description": "Asphalt Paving Contractors"}},
      "serviceAreasString": ""},
     {"name": "Cazco Seamless Guttering", "mid": "0136751139", "emid": "mr0vbpv",
                                  "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
                                  "url": "/c/mr0vbpv/cazco-seamless-guttering", "claimStatus": "UNCLAIMED",
                                  "location": {"address": "1309 North Redwood Drive", "city": "Independence",
                                               "stateAbbrv": "MO", "postalCode": "64056"},
                                  "contactInfo": {"phone": "8162575088"},
                                  "products": {"productTerms": {"count": 0, "list": []}},
                                  "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
                                  "industry": {"sic2": {"code": "E0", "description": "Construction"},
                                               "sic4": {"code": "E02F9",
                                                        "description": "Roofing, Siding, and Sheet Metal Work"},
                                               "sicm": {"code": "E02F902T", "description": "Gutters and Downspouts"}},
                                  "serviceAreasString": ""},
     {"name": "M & R Custom Fence", "mid": "0310797341", "emid": "mb53gbn",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mb53gbn/m-r-custom-fence", "claimStatus": "UNCLAIMED",
      "location": {"address": "1844 South Norton Avenue", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64052"},
      "contactInfo": {"phone": "8164569761", "website": "http://www.myfenceguy.com"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E031F", "description": "Special Trade Contractors, NEC"},
                   "sicm": {"code": "E031F7NC", "description": "Fence Contractors"}}, "serviceAreasString": ""},
     {"name": "Wb Painting", "mid": "0308931240", "emid": "mb0jzjp",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mb0jzjp/wb-painting", "claimStatus": "UNCLAIMED",
      "location": {"address": "926 South Leslie Street", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64050"}, "contactInfo": {"phone": "8165910660"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E02D1", "description": "Painting and Paper Hanging"},
                   "sicm": {"code": "E02D1000", "description": "Painters"}}, "serviceAreasString": ""},
     {"name": "Ogle Contracting", "mid": "0010159173", "emid": "mmcmm2k",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mmcmm2k/ogle-contracting", "claimStatus": "UNCLAIMED",
      "location": {"address": "14700 East Mayes Road", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64050"}, "contactInfo": {"phone": "8168067078"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E031F", "description": "Special Trade Contractors, NEC"},
                   "sicm": {"code": "E031F000", "description": "Contractors"}}, "serviceAreasString": ""},
     {"name": "Advantage Plus Overhead Door", "mid": "0017381388", "emid": "mmg4fyz",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mmg4fyz/advantage-plus-overhead-door", "claimStatus": "UNCLAIMED",
      "location": {"address": "637 East Gudgell Avenue", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64055"}, "contactInfo": {"phone": "8168360893"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E00D3", "description": "Lumber and Other Building Materials Dealers"},
                   "sicm": {"code": "E00D305N", "description": "Garage Doors"}}, "serviceAreasString": ""},
     {"name": "US Pallet Supply Inc", "mid": "0032979807", "emid": "mtrstxy",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mtrstxy/us-pallet-supply-inc", "claimStatus": "UNCLAIMED",
      "location": {"address": "1517 North Main Street", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64050"}, "contactInfo": {"phone": "8162524884"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E001F", "description": "Lumber, Plywood, Millwork, and Wood Panels"},
                   "sicm": {"code": "E001F7N7", "description": "Wholesale Pallets and Skids"}},
      "serviceAreasString": ""},
     {"name": "Asphaltic Surfaces LLC", "mid": "0237691573", "emid": "mk1cdy9",
                                  "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
                                  "url": "/c/mk1cdy9/asphaltic-surfaces-llc", "claimStatus": "UNCLAIMED",
                                  "location": {"address": "417 South Spring Street", "city": "Independence",
                                               "stateAbbrv": "MO", "postalCode": "64050"},
                                  "contactInfo": {"phone": "8163135466",
                                                  "website": "http://www.homeadvisor.com/rated.AsphalticSurfacesLLC.83500835.html"},
                                  "products": {"productTerms": {"count": 0, "list": []}},
                                  "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
                                  "industry": {"sic2": {"code": "E0", "description": "Construction"},
                                               "sic4": {"code": "E026X",
                                                        "description": "Highway and Street Construction, Except Elevated Highways"},
                                               "sicm": {"code": "E026X05K", "description": "Paving Contractors"}},
                                  "serviceAreasString": ""},
     {"name": "Fiesta Party Rental", "mid": "0238700849", "emid": "mkb2j67",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mkb2j67/fiesta-party-rental", "claimStatus": "UNCLAIMED",
      "location": {"address": "11028 East 23rd Street South", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64052"}, "contactInfo": {"phone": "8167722977"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0167", "description": "Equipment Rental and Leasing, NEC"},
                   "sicm": {"code": "E0167000", "description": "Yard Equipment Rental Stores"}},
      "serviceAreasString": ""},
     {"name": "Downey Construction Inc", "mid": "0306942863", "emid": "mbscxfn",
                                  "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
                                  "url": "/c/mbscxfn/downey-construction-inc", "claimStatus": "UNCLAIMED",
                                  "location": {"address": "3626 East Noland Court B", "city": "Independence",
                                               "stateAbbrv": "MO", "postalCode": "64055"},
                                  "contactInfo": {"phone": "8163731092"},
                                  "products": {"productTerms": {"count": 0, "list": []}},
                                  "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
                                  "industry": {"sic2": {"code": "E0", "description": "Construction"},
                                               "sic4": {"code": "E0209",
                                                        "description": "General Contractors-Single-Family Houses"},
                                               "sicm": {"code": "E02097Y4", "description": "General Contractors"}},
                                  "serviceAreasString": ""},
     {"name": "Tuff Shed, Inc", "mid": "0226903329", "emid": "mhqnjnh",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mhqnjnh/tuff-shed-inc", "claimStatus": "UNCLAIMED",
      "location": {"address": "1719 South Noland Road", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64055"}, "contactInfo": {"phone": "8164279629", "website": "http://www.tuffshed.com"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E01C4", "description": "Prefabricated Wood Buildings and Components"},
                   "sicm": {"code": "E01C4000", "description": "Prefabricated Wood Buildings"}},
      "serviceAreasString": ""},
     {"name": "Gemmas Painting LLC", "mid": "0233958664", "emid": "mkwbbbn",
                                  "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
                                  "url": "/c/mkwbbbn/gemmas-painting-llc", "claimStatus": "UNCLAIMED",
                                  "location": {"address": "20004 East 16th Street North", "city": "Independence",
                                               "stateAbbrv": "MO", "postalCode": "64056"},
                                  "contactInfo": {"phone": "8165489270"},
                                  "products": {"productTerms": {"count": 0, "list": []}},
                                  "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
                                  "industry": {"sic2": {"code": "E0", "description": "Construction"},
                                               "sic4": {"code": "E02D1", "description": "Painting and Paper Hanging"},
                                               "sicm": {"code": "E02D1000", "description": "Painters"}},
                                  "serviceAreasString": ""},
     {"name": "Jc Seamless Guttering LLC", "mid": "0226546411", "emid": "mhq13ky",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mhq13ky/jc-seamless-guttering-llc", "claimStatus": "UNCLAIMED",
      "location": {"address": "1708 Highland Drive", "city": "Independence", "stateAbbrv": "MO", "postalCode": "64057"},
      "contactInfo": {"phone": "8163323162",
                      "website": "http://www.homeadvisor.com/rated.JCSeamlessGuttering.44273097.html"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E02F9", "description": "Roofing, Siding, and Sheet Metal Work"},
                   "sicm": {"code": "E02F902T", "description": "Gutters and Downspouts"}}, "serviceAreasString": ""},
     {"name": "Marshall Home Repair, LLC", "mid": "0210076208", "emid": "mhb288p",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mhb288p/marshall-home-repair-llc", "claimStatus": "UNCLAIMED",
      "location": {"address": "1334 North Liberty Street", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64050"}, "contactInfo": {"phone": "8162860377"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E020902T", "description": "Mobile Homes-Improvements"}}, "serviceAreasString": ""},
     {"name": "Alfa Roofing & Remodeling", "mid": "0208421721", "emid": "mhknrtb",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mhknrtb/alfa-roofing-remodeling", "claimStatus": "UNCLAIMED",
      "location": {"address": "228 East Bellevista Drive", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64055"}, "contactInfo": {"phone": "9139532620"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E020902T", "description": "Mobile Homes-Improvements"}}, "serviceAreasString": ""},
     {"name": "E & E Quality Builders, Inc", "mid": "0206238919", "emid": "mhx158c",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mhx158c/e-e-quality-builders-inc", "claimStatus": "UNCLAIMED",
      "location": {"address": "18115 Holke Road", "city": "Independence", "stateAbbrv": "MO", "postalCode": "64057"},
      "contactInfo": {"phone": "8167165525", "website": "http://www.eandequalitybuilders.com"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E02097N1", "description": "Building Contractors"}}, "serviceAreasString": ""},
     {"name": "Midland Concrete Leveling", "mid": "0205599024", "emid": "mhwdc0g",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mhwdc0g/midland-concrete-leveling", "claimStatus": "UNCLAIMED",
      "location": {"address": "3601 North Spring Street", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64050"},
      "contactInfo": {"phone": "8164575988", "website": "http://www.midlandconcretelevelingllc.com"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0303", "description": "Concrete Work"},
                   "sicm": {"code": "E0303000", "description": "Concrete Contractors"}}, "serviceAreasString": ""},
     {"name": "Alvested Services Inc", "mid": "0038714323", "emid": "mtbq32r",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mtbq32r/alvested-services-inc", "claimStatus": "UNCLAIMED",
      "location": {"address": "335 North Downey Avenue", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64056"}, "contactInfo": {"phone": "8162540718"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E020902S", "description": "Home Improvements"}}, "serviceAreasString": ""},
     {"name": "Dandorf Construction Inc", "mid": "0038730909", "emid": "mtbzvsw",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mtbzvsw/dandorf-construction-inc", "claimStatus": "UNCLAIMED",
      "location": {"address": "18201 Hidden Valley Road", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64057"}, "contactInfo": {"phone": "8167955888"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E02097N1", "description": "Building Contractors"}}, "serviceAreasString": ""},
     {"name": "Tommy's Concrete", "mid": "0305629186", "emid": "mb8z92m",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mb8z92m/tommy-s-concrete", "claimStatus": "UNCLAIMED",
      "location": {"address": "10613 East 37th Street South", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64052"},
      "contactInfo": {"phone": "9139279791", "website": "http://Tommysconcrete.com"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0303", "description": "Concrete Work"},
                   "sicm": {"code": "E0303000", "description": "Concrete Contractors"}}, "serviceAreasString": ""},
     {"name": "Budget Builder Lc", "mid": "0310507440", "emid": "mb5x5nt",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mb5x5nt/budget-builder-lc", "claimStatus": "UNCLAIMED",
      "location": {"address": "828 South Trail Ridge Drive", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64050"}, "contactInfo": {"phone": "8168331678"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E02097N1", "description": "Building Contractors"}}, "serviceAreasString": ""},
     {"name": "Fonzie's Auto And Home Repair LLC", "mid": "0309435588", "emid": "mb4tpbw",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mb4tpbw/fonzie-s-auto-and-home-repair-llc", "claimStatus": "UNCLAIMED",
      "location": {"address": "1501 North Courtney Road", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64050"}, "contactInfo": {"phone": "8168965350"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E020902T", "description": "Mobile Homes-Improvements"}}, "serviceAreasString": ""},
     {"name": "K & L Roofing & General Contracting, LLC", "mid": "0309196456", "emid": "mb005jh",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mb005jh/k-l-roofing-general-contracting-llc", "claimStatus": "UNCLAIMED",
      "location": {"address": "3404 South Crysler Avenue", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64055"},
      "contactInfo": {"phone": "8168865026", "website": "http://www.klroofingmo.com"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E02F9", "description": "Roofing, Siding, and Sheet Metal Work"},
                   "sicm": {"code": "E02F902V", "description": "Roofing Contractors"}}, "serviceAreasString": ""},
     {"name": "Follow Me Construction And Maintenance", "mid": "0209539209", "emid": "mh1pdpb",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mh1pdpb/follow-me-construction-and-maintenance", "claimStatus": "UNCLAIMED",
      "location": {"address": "11106 East Winner Road", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64052"},
      "contactInfo": {"phone": "8168449590", "website": "http://www.followmeconstruction.com"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E0209000", "description": "Home Builders"}}, "serviceAreasString": ""},
     {"name": "C & D Roofing", "mid": "0052514797", "emid": "mt45y6s",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mt45y6s/c-d-roofing", "claimStatus": "UNCLAIMED",
      "location": {"city": "Independence", "stateAbbrv": "MO", "postalCode": "64056"},
      "contactInfo": {"phone": "8162574800"}, "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E02F9", "description": "Roofing, Siding, and Sheet Metal Work"},
                   "sicm": {"code": "E02F902V", "description": "Roofing Contractors"}}, "serviceAreasString": ""},
     {"name": "Sky Roofing", "mid": "0156252352", "emid": "mw2wzj2",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mw2wzj2/sky-roofing", "claimStatus": "UNCLAIMED",
      "location": {"address": "911 North NOLAND Road", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64050"},
      "contactInfo": {"phone": "8163477444", "website": "http://www.skylineroofllc.com/"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E02F9", "description": "Roofing, Siding, and Sheet Metal Work"},
                   "sicm": {"code": "E02F902U", "description": "Roof Maintenance"}}, "serviceAreasString": ""},
     {"name": "Tgp Remodeling", "mid": "0235166416", "emid": "mkxdp9f",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mkxdp9f/tgp-remodeling", "claimStatus": "UNCLAIMED",
      "location": {"address": "2210 South Overton Avenue", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64052"}, "contactInfo": {"phone": "7857306586"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E020902T", "description": "Mobile Homes-Improvements"}}, "serviceAreasString": ""},
     {"name": "Danco Pallet", "mid": "0156123372", "emid": "mw2tdk4",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mw2tdk4/danco-pallet", "claimStatus": "UNCLAIMED",
      "location": {"address": "1415 South Ash Avenue", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64052"}, "contactInfo": {}, "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E01C0", "description": "Wood Pallets and Skids"},
                   "sicm": {"code": "E01C005K", "description": "Pallets, Wood and Wood With Metal"}},
      "serviceAreasString": ""}]},
     "industry": {"type": "sic4", "count": 34,
     "list": [
    {"label": "Brick, Stone and Related Construction Materials", "code": "E0020", "count": 1,
     "link": "/mb_54_E0020_BF3/brick_stone_and_related_construction_materials/independence_mo"},
    {"label": "Carpentry Work", "code": "E02EF", "count": 8, "link": "/mb_54_E02EF_BF3/carpentry_work/independence_mo"},
    {"label": "Commercial General Contractors", "code": "E021E", "count": 14,
     "link": "/mb_54_E021E_BF3/commercial_general_contractors/independence_mo"},
    {"label": "Concrete Work", "code": "E0303", "count": 45, "link": "/mb_54_E0303_BF3/concrete_work/independence_mo"},
    {"label": "Construction and Mining (Except Petroleum) Machinery and Equipment", "code": "E0052", "count": 5,
     "link": "/mb_54_E0052_BF3/construction_and_mining_except_petroleum_machinery_and_equipment/independence_mo"},
    {"label": "Equipment Rental and Leasing, NEC", "code": "E0167", "count": 25,
     "link": "/mb_54_E0167_BF3/equipment_rental_and_leasing_nec/independence_mo"},
    {"label": "Excavation Work", "code": "E031A", "count": 11,
     "link": "/mb_54_E031A_BF3/excavation_work/independence_mo"},
    {"label": "Floor Installation", "code": "E02F0", "count": 9,
     "link": "/mb_54_E02F0_BF3/floor_installation/independence_mo"},
    {"label": "General Contractors-Residential Buildings, Other Than Single-Family", "code": "E020A", "count": 11,
     "link": "/mb_54_E020A_BF3/general_contractors_residential_buildings_other_than_single_family/independence_mo"},
    {"label": "General Contractors-Single-Family Houses", "code": "E0209", "count": 157,
     "link": "/mb_54_E0209_BF3/general_contractors_single_family_houses/independence_mo"},
    {"label": "Glass and Glazing Work", "code": "E0319", "count": 2,
     "link": "/mb_54_E0319_BF3/glass_and_glazing_work/independence_mo"},
    {"label": "Hardwood Dimension and Flooring Mills", "code": "E01AA", "count": 1,
     "link": "/mb_54_E01AA_BF3/hardwood_dimension_and_flooring_mills/independence_mo"},
    {"label": "Heavy Construction, NEC", "code": "E0275", "count": 3,
     "link": "/mb_54_E0275_BF3/heavy_construction_nec/independence_mo"},
    {"label": "Highway and Street Construction, Except Elevated Highways", "code": "E026X", "count": 11,
     "link": "/mb_54_E026X_BF3/highway_and_street_construction_except_elevated_highways/independence_mo"},
    {"label": "Installation or Erection of Building Equipment, NEC", "code": "E031C", "count": 1,
     "link": "/mb_54_E031C_BF3/installation_or_erection_of_building_equipment_nec/independence_mo"},
    {"label": "Lumber and Other Building Materials Dealers", "code": "E00D3", "count": 13,
     "link": "/mb_54_E00D3_BF3/lumber_and_other_building_materials_dealers/independence_mo"},
    {"label": "Lumber, Plywood, Millwork, and Wood Panels", "code": "E001F", "count": 4,
     "link": "/mb_54_E001F_BF3/lumber_plywood_millwork_and_wood_panels/independence_mo"},
    {"label": "Masonry, Stone Setting, and Other Stone Work", "code": "E02E5", "count": 10,
     "link": "/mb_54_E02E5_BF3/masonry_stone_setting_and_other_stone_work/independence_mo"},
    {"label": "Mobile Homes", "code": "E01C3", "count": 2, "link": "/mb_54_E01C3_BF3/mobile_homes/independence_mo"},
    {"label": "Painting and Paper Hanging", "code": "E02D1", "count": 49,
     "link": "/mb_54_E02D1_BF3/painting_and_paper_hanging/independence_mo"},
    {"label": "Paperboard Mills", "code": "E0277", "count": 1,
     "link": "/mb_54_E0277_BF3/paperboard_mills/independence_mo"},
    {"label": "Plumbing and Heating Equipment and Supplies (Hydronics)", "code": "E004A", "count": 6,
     "link": "/mb_54_E004A_BF3/plumbing_and_heating_equipment_and_supplies_hydronics_/independence_mo"},
    {"label": "Prefabricated Wood Buildings and Components", "code": "E01C4", "count": 1,
     "link": "/mb_54_E01C4_BF3/prefabricated_wood_buildings_and_components/independence_mo"},
    {"label": "Roofing, Siding, and Sheet Metal Work", "code": "E02F9", "count": 65,
     "link": "/mb_54_E02F9_BF3/roofing_siding_and_sheet_metal_work/independence_mo"},
    {"label": "Special Trade Contractors, NEC", "code": "E031F", "count": 44,
     "link": "/mb_54_E031F_BF3/special_trade_contractors_nec/independence_mo"},
    {"label": "Structural Steel Erection", "code": "E0317", "count": 2,
     "link": "/mb_54_E0317_BF3/structural_steel_erection/independence_mo"},
    {"label": "Terrazzo, Tile, Marble, and Mosaic Work", "code": "E02E7", "count": 10,
     "link": "/mb_54_E02E7_BF3/terrazzo_tile_marble_and_mosaic_work/independence_mo"},
    {"label": "Wall Construction", "code": "E02E6", "count": 9,
     "link": "/mb_54_E02E6_BF3/wall_construction/independence_mo"},
    {"label": "Warm Air Heating and Air-Conditioning Equipment and Supplies", "code": "E004B", "count": 2,
     "link": "/mb_54_E004B_BF3/warm_air_heating_and_air_conditioning_equipment_and_supplies/independence_mo"},
    {"label": "Water, Sewer, Pipeline, and Communications and Power Line Construction", "code": "E026F", "count": 8,
     "link": "/mb_54_E026F_BF3/water_sewer_pipeline_and_communications_and_power_line_construction/independence_mo"},
    {"label": "Wood Containers", "code": "E01C1", "count": 1,
     "link": "/mb_54_E01C1_BF3/wood_containers/independence_mo"},
    {"label": "Wood Kitchen Cabinets", "code": "E01B2", "count": 1,
     "link": "/mb_54_E01B2_BF3/wood_kitchen_cabinets/independence_mo"},
    {"label": "Wood Pallets and Skids", "code": "E01C0", "count": 1,
     "link": "/mb_54_E01C0_BF3/wood_pallets_and_skids/independence_mo"},
    {"label": "Wrecking and Demolition Work", "code": "E031B", "count": 5,
     "link": "/mb_54_E031B_BF3/wrecking_and_demolition_work/independence_mo"}]},
     "geography": {"type": "sisterCity", "more": 'true', "totalCount": 1019, "count": 10, "list": [
     {"label": "Saint Louis", "count": 3323, "link": "/mb_53_E0_BOV/construction/saint_louis_mo", "code": "BOV"},
     {"label": "Kansas City", "count": 2464, "link": "/mb_53_E0_BFP/construction/kansas_city_mo", "code": "BFP"},
     {"label": "Springfield", "count": 1305, "link": "/mb_53_E0_BQ1/construction/springfield_mo", "code": "BQ1"},
     {"label": "Columbia", "count": 728, "link": "/mb_53_E0_B84/construction/columbia_mo", "code": "B84"},
     {"label": "Saint Charles", "count": 581, "link": "/mb_53_E0_BOQ/construction/saint_charles_mo", "code": "BOQ"},
     {"label": "Independence", "count": 538, "link": "/mb_53_E0_BF3/construction/independence_mo", "code": "BF3"},
     {"label": "Joplin", "count": 515, "link": "/mb_53_E0_BFM/construction/joplin_mo", "code": "BFM"},
     {"label": "Jefferson City", "count": 496, "link": "/mb_53_E0_BFH/construction/jefferson_city_mo", "code": "BFH"},
     {"label": "O Fallon", "count": 487, "link": "/mb_53_E0_BL2/construction/o_fallon_mo", "code": "BL2"},
     {"label": "Saint Joseph", "count": 457, "link": "/mb_53_E0_BOU/construction/saint_joseph_mo", "code": "BOU"}]},
     "featuredCompanies":
         {"count": 10,
          "list": [
     {"name": "Ricks Remodeling & Renovations", "mid": "0136049869", "emid": "mry14r2",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131017UHEKgjZ8jQ",
      "url": "/c/mry14r2/ricks-remodeling-renovations", "claimStatus": "CLAIMED",
      "shortDescription": " Remodeling & Renovations\r\nHome Repairs, Remodeling, Bathroom, Basement and Kitchen Remodels/",
      "detailedDescription": "I am Self Employed. I am Quality, Fast Friendly Minded.\r\nI am a Licensed Contractor in the City Of Independence.\r\n I have been in Business for 30 plus yrs.\r\n\r\nI Specialize in Bathroom, Basement and Kitchen Remodels.\r\nI do Framing, Insulating, Electrical, Plumbing, Sheetrock hanging, Painting, Tiling, Knockdown Texture on Walls and Ceilings.\r\nWood Rot Repair, All Handy Man Services.\r\nI have Excellent References.\r\n",
      "location": {"address": "10313 E 9th Street S", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64053"},
      "contactInfo": {"phone": "(816)254-0140", "website": "www.ricksremodelingrenovations.com"}, "products": {
         "productTerms": {"count": 5,
                          "list": [{"name": "Renovation Services"}, {"name": "Home Improvement And Repair Services"},
                                   {"name": "Plumbing Remodeling Services"}, {"name": "Home Improvement Services"},
                                   {"name": "Basement Remodeling Services"}]}},
      "recommendations": {"averageRating": {"ratingCount": 1, "ratingValue": 5}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0209", "description": "General Contractors-Single-Family Houses"},
                   "sicm": {"code": "E02098PW", "description": "Bathroom Remodeling"}}, "serviceAreasString": ""},
     {"name": "Arrowhead Door CO", "mid": "0039950330", "emid": "mt7kmdb",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20170330UYqk3u8Gn9",
      "url": "/c/mt7kmdb/arrowhead-door-co", "claimStatus": "CLAIMED", "shortDescription": "Arrowhead Door CO",
      "location": {"address": "15503 East 43rd Terrace South", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64055"}, "contactInfo": {"phone": "8163738228"},
      "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 1, "ratingValue": 2}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E00D3", "description": "Lumber and Other Building Materials Dealers"},
                   "sicm": {"code": "E00D305N", "description": "Garage Doors"}}, "serviceAreasString": ""},
     {"name": "Pure Construction LLC", "mid": "0234769778", "emid": "mkxxlc8",
      "logo": "https://images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
      "url": "/c/mkxxlc8/pure-construction-llc", "claimStatus": "CLAIMED",
      "location": {"address": "1302 S Scott", "city": "Independence", "stateAbbrv": "MO", "postalCode": "64053"},
      "contactInfo": {"phone": "816 382-7792"}, "products": {"productTerms": {"count": 0, "list": []}},
      "recommendations": {"averageRating": {"ratingCount": 1, "ratingValue": 1}},
      "industry": {"sic2": {"code": "Construction"}, "sic4": {"code": "Special Trade Contractors, NEC"},
                   "sicm": {"code": "E031F0GU", "description": "Kitchen and Bathroom Remodeling"}},
      "serviceAreasString": ""},
     {"name": "Phil's Window & Door Service, Inc", "mid": "0029995962", "emid": "mtt2pkn",
                                  "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
                                  "url": "/c/mtt2pkn/phil-s-window-door-service-inc", "claimStatus": "UNCLAIMED",
                                  "location": {"address": "3115 South Overton Avenue", "city": "Independence",
                                               "stateAbbrv": "MO", "postalCode": "64052"},
                                  "contactInfo": {"phone": "8163657153"},
                                  "products": {"productTerms": {"count": 0, "list": []}},
                                  "recommendations": {"averageRating": {"ratingCount": 1, "ratingValue": 5}},
                                  "industry": {"sic2": {"code": "E0", "description": "Construction"},
                                               "sic4": {"code": "E031C",
                                                        "description": "Installation or Erection of Building Equipment, NEC"},
                                               "sicm": {"code": "E031C000",
                                                        "description": "Installing Building Equipment"}},
                                  "serviceAreasString": ""},
     {"name": "MJZ, LLC", "mid": "0238157052", "emid": "mk1pk9l",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20200108VERZ7mLin4",
      "url": "/c/mk1pk9l/mjz-llc", "claimStatus": "CLAIMED",
      "shortDescription": "MJZ, LLC is a Remodeling Company in Independence, MO",
      "detailedDescription": "Welcome to MJZ, LLC, your premier option for remodeling and handyman services in Independence, MO and the surrounding area. MJZ, LLC can handle all your home remodels in one place, ensuring that you get a property that looks and works in all the ways you want it to. Our mission is to provide quality service that exceeds your expectations as a customer, from start to finish. We continually strive to ensure your dreams develop into reality. Our company prides itself on maintaining clean work environments and completing tasks in the most efficient manner available. Our goal as a company is to provide an ever-increasing scope of service solutions to fit your needs, so as to truly provide \"an infinite range of possibilities\".",
      "location": {"address": "Service Area", "city": "Independence", "stateAbbrv": "MO", "postalCode": "64055"},
      "contactInfo": {"phone": "(816) 623-2482", "website": "http://www.independencedeckrepair.com"}, "products": {
         "productTerms": {"count": 5, "list": [{"name": "Fence Contractor"}, {"name": "Deck Installation"},
                                               {"name": "Drywall Contractor"}, {"name": "Kitchen Remodeling"},
                                               {"name": "Deck Repair"}]}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E031F", "description": "Special Trade Contractors, NEC"},
                   "sicm": {"code": "E031F0GU", "description": "Kitchen and Bathroom Remodeling"}},
      "serviceAreasString": ""},
     {"name": "Bellis Guttering", "mid": "0134934308", "emid": "mrs9c1d",
                                  "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20110509ZATYu1ROjb",
                                  "url": "/c/mrs9c1d/bellis-guttering", "claimStatus": "CLAIMED",
                                  "shortDescription": "Full service gutter and downspout installation contractors",
                                  "detailedDescription": "Serving Kansas and Missouri homeowners with expertise and efficiency, we offer state-of-the-art gutter and downspout installation and design services that are built to protect your home and your property. Our experienced experts are ready to help you by providing service that only skill and experience can offer. In addition to seamless gutters, we provide the installation and repair of all types of custom and legacy gutter systems, siding, and windows. Bellis Guttering is fully dedicated and committed to providing you with hassle-free and cost-effective solutions for all of your specific needs.",
                                  "location": {"address": "1516 N Geronimo Dr", "city": "Independence",
                                               "stateAbbrv": "MO", "postalCode": "64058"},
                                  "contactInfo": {"phone": "816-443-4002",
                                                  "website": "http://kansascitygutterservices.com/"}, "products": {
             "productTerms": {"count": 4, "list": [{"name": "Rain Gutter"}, {"name": "Gutter Design"},
                                                   {"name": "Gutter Maintenance"},
                                                   {"name": "Downspout Installation"}]}},
                                  "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
                                  "industry": {"sic2": {"code": "E0", "description": "Construction"},
                                               "sic4": {"code": "E02F9",
                                                        "description": "Roofing, Siding, and Sheet Metal Work"},
                                               "sicm": {"code": "E02F902T", "description": "Gutters and Downspouts"}},
                                  "serviceAreasString": ""},
     {"name": "Jazzy Custom Homes", "mid": "0061371570", "emid": "mvr2vxv",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20110106liRqFExqxy",
      "url": "/c/mvr2vxv/jazzy-custom-homes", "claimStatus": "CLAIMED",
      "shortDescription": "Kansas City Home Remodeling Contractor serving the surrounding Metro Area. Specializing in Kitchen Remodeling, Bathroom Remodeling and Basements",
      "detailedDescription": "Jazzy Custom Homes is an organization that specializes is carpentry builds and general construction renovations. From home renovations and patios to custom architecture, We pride ourselves on meeting and exceeding your expectations while maintaining the set budget for your home projects. \r\n\r\nAt Jazzy, We hands on design and build from start to finish.  This reduces cost and ensures that quality remains a constant. Amongst the portfolio of services we offer they all carry the same result; create a functional and appealing addition or renovation to fit your needs.",
      "location": {"address": "15100 E 43rd St.", "city": "Independence", "stateAbbrv": "MO", "postalCode": "64055"},
      "contactInfo": {"phone": "816-237-0677", "website": "www.JazzyCustomHomes.com"}, "products": {
         "productTerms": {"count": 5,
                          "list": [{"name": "Basement Remodeling Services"}, {"name": "Bathroom Remodeling"},
                                   {"name": "Home Repair Services"}, {"name": "Kitchen Remodeling Services"},
                                   {"name": "Landscape Services"}]}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E031F", "description": "Special Trade Contractors, NEC"},
                   "sicm": {"code": "E031F0GU", "description": "Kitchen and Bathroom Remodeling"}},
      "serviceAreasString": ""},
     {"name": "Duncan Gutter Inc.", "mid": "0261459057", "emid": "m1r9f0r",
                                  "logo": "https://images.manta-r3.com/api/claim-this-profile/image-mgr/view/20131121x98IS7WjQj",
                                  "url": "/c/m1r9f0r/duncan-gutter-inc-", "claimStatus": "CLAIMED",
                                  "shortDescription": "Duncan Gutter Inc. - (816) 591-8566",
                                  "detailedDescription": "For homeowners seeking gutter installation and cleaning services, Duncan Gutter Inc. should be your gutter cleaner of choice. Our cleaning work is also carried out without any mess.\n\nWe serve in Independence, MO, Bates City MI; and the surrounding areas.\n\nGutter Repair, Gutter Installation, Leaf Protection, Gutter Replacement, Gutter Covers\nGutter Covers Installation, Gutter Replacement Service, Leafless Gutter",
                                  "location": {"address": "322 S Kentucky Ave.", "city": "Independence",
                                               "stateAbbrv": "MO", "postalCode": "64053"},
                                  "contactInfo": {"phone": "(816) 591-8566", "website": "https://duncangutterinc.com/"},
                                  "products": {"productTerms": {"count": 0, "list": []}},
                                  "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
                                  "industry": {"sic2": {"code": "Construction"},
                                               "sic4": {"code": "Roofing, Siding, and Sheet Metal Work"},
                                               "sicm": {"code": "E02F902S", "description": "Roofing and gutter work"}},
                                  "serviceAreasString": ""},
     {"name": "Asphalt Wizards", "mid": "0195908396", "emid": "mx5rvpn",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20160205SxVieM53jj",
      "url": "/c/mx5rvpn/asphalt-wizards", "claimStatus": "CLAIMED",
      "shortDescription": "Asphalt Wizards serves the entire Kansas City Metro Area.",
      "detailedDescription": "Asphalt Wizards serves the entire Kansas City Metro Area.  We are a full service paving company that specializes in providing pavement solutions in a timely manner.  Our crew is experienced and we have top of the line equipment to take on any size project.",
      "location": {"address": "517 Lacy Rd", "city": "Independence", "stateAbbrv": "MO", "postalCode": "64050"},
      "contactInfo": {"phone": "8168330200", "website": "http://www.asphaltwizards.com"}, "products": {
         "productTerms": {"count": 1, "list": [{
                                                   "name": "Asphalt Contractor , Asphalt Sealcoating ,Parking Lot Striping, Asphalt Sealing, Parking Lot Maintenance, Concrete Contractor, Asphalt Paving"}]}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E0303", "description": "Concrete Work"},
                   "sicm": {"code": "E0303000", "description": "Concrete Contractors"}}, "serviceAreasString": ""},
     {"name": "JV Garage Door, LLC", "mid": "0184836859", "emid": "mx2r2tb",
      "logo": "//images.manta-r3.com/api/claim-this-profile/image-mgr/view/20120806vMD2XNErEP",
      "url": "/c/mx2r2tb/jv-garage-door-llc", "claimStatus": "CLAIMED",
      "shortDescription": " Quality residential and commercial installation, repair and maintenance on all garage doors and equipment including custom doors, wood doors, openers",
      "location": {"address": "15212 East 33rd Street South", "city": "Independence", "stateAbbrv": "MO",
                   "postalCode": "64055"},
      "contactInfo": {"phone": "(816) 5168872", "website": "http://www.jvgaragedoor.com/"}, "products": {
         "productTerms": {"count": 5,
                          "list": [{"name": "Door Balancing Services"}, {"name": "Door Components And Hardware"},
                                   {"name": "Doors"}, {"name": "Garage Door Opener Remote Controls"},
                                   {"name": "Garage Door Openers"}]}},
      "recommendations": {"averageRating": {"ratingCount": 0, "ratingValue": 0}},
      "industry": {"sic2": {"code": "E0", "description": "Construction"},
                   "sic4": {"code": "E00D3", "description": "Lumber and Other Building Materials Dealers"},
                   "sicm": {"code": "E00D305N", "description": "Garage Doors"}}, "serviceAreasString": ""}]}}

for j in x["companies"]['list']:
    print(j)